### ISSUE TITLE
The service "webtown_kunstmaan_extension.translation.kunstmaan_extractor" has a dependency on a non-existent service "jms_translation.doc_parser"

### ISSUE THREAD

**Issue by KevinSleegers** [webtown-php/KunstmaanExtensionBundle#9]
Hi,

I've recently found out about this bundle, and it looks like it might be really helpful for our Kunstmaan project. 

Installation went fine, but for some reason I keep getting the following error:
`The service "webtown_kunstmaan_extension.translation.kunstmaan_extractor" has a dependency on a non-existent service "jms_translation.doc_parser"`

I'm using the latest version of Kunstmaan, version 4.0.

Can you tell me what I did wrong, or is this bundle not compatible with that version of the Kunstmaan CMS?

Thanks,
Kevin

**Comment by fchris82** [comment]
Sorry, I forgot the `JMSTranslationBundle()` from the `README.md`. You have to add the `new JMS\TranslationBundle\JMSTranslationBundle()` to `AppKernel.php` also!

```php
<?php
// app/AppKernel.php

// ...
class AppKernel extends Kernel
{
    public function registerBundles()
    {
        $bundles = array(
            // ...

            new Webtown\KunstmaanExtensionBundle\WebtownKunstmaanExtensionBundle(),
            new JMS\TranslationBundle\JMSTranslationBundle(),
        );

        // ...
    }

    // ...
}
```
